name: Build Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v4

      - name: Install Android SDK
        run: |
          sdkmanager "platform-tools" \
                     "platforms;android-36" \
                     "build-tools;36.0.0"
          yes | sdkmanager --licenses || true

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '8.11'

      - name: Build Debug APK
        run: gradle assembleDebug

      - name: Build Release APK
        run: gradle assembleRelease

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: Librum-debug
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: Librum-release
          path: app/build/outputs/apk/release/*.apk